orders.settings:
  type: config_object
  label: 'Orders config.'
  mapping:
    gst_types:
      mapping:
        value:
          type: Integer
          label: 'The GST to apply'
        value_label:
          type: string
          label: 'Text to show'
